### ISSUE TITLE
Adapt code for pandas 0.18

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/opengrid#127]

**Comment by JrtPec** [comment]
@saroele I believe we should move forward with this, tmpo is giving me IndexErrors on pandas 0.17 which I don't get on pandas 0.18...
@icarus75 I sent you an e-mail on this a couple of weeks ago, thinking it was an issue with tmpo-blocks, but it looks like it is a bug with pandas 0.17

**Comment by JrtPec** [comment]
@kdebrab I remember when you told us exactly why and how upgrading to pandas 0.18 would cause problems... would you mind refreshing my memory?

**Comment by kdebrab** [comment]
The main cause of problems when upgrading to 0.18 are changes in .resample(). The quick solution is to make sure the optional (but deprecated) parameter 'how' is always specified (in other words, make sure to include how='mean' whenever it is missing), then everything will work as before, apart from the FutureWarnings you get. In order to avoid also the FutureWarnings one can do:
```python
from distutils.version import StrictVersion
if StrictVersion(pd.__version__) >= '0.18.0':
    df2 = df1.resample(rule).mean()
else:
    df2 = df1.resample(rule, how='mean')
```

**Comment by JrtPec** [comment]
Yesterday, I heard somebody ( @saroele ) say (I'm paraphrasing): "I'm not adapting to Pandas 0.18, I'll go straight for 0.19"
... which was released 3 days ago: http://pandas.pydata.org

**Comment by saroele** [comment]
I should have said that I'll go straight to 1.0, that would have saved my
ass for a couple years... :-)
ok, good point to shift to 0.19.
