### ISSUE TITLE
Job per graph

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#38]
Our graphs are developed in IPython notebooks.  We have to create cron jobs for automatically generating the new graphs every day. 

- converting notebook to .py (maybe not needed if this works: http://stackoverflow.com/a/17913858/566942
- creating a crontab job

For the crontab file, the best will be to put the file in our opengrid repo so we can track changes to the file and deploy a new file easily with ``crontab ourfile`` after pulling a new version on the droplet.

**Comment by saroele** [comment]
I currently use crontab to schedule the jobs individually. The crontab setup is stored in [crontab.txt](https://github.com/opengridcc/opengrid/blob/develop/notebooks/crontab.txt).  Currently, there are 3 jobs:
- sync tmpo database (hourly)
- create the timeseries plots (hourly, starts 5 minutes later)
- create the electricity standby plots (every morning 5h30 UTC). 

We can easily add graphs in this framework, so I'll close this issue.  We can create a more SMART issue if the current approach is not sufficient any longer.

**Comment by JrtPec** [comment]
In connection with #99 and opengridcc/website#24, I have a feeling that there is some other script running which is permanently connected to the tmpo-database, or one of these three processes doesn't terminate correctly.

When I wrote the download to CSV functionality I fully expected that it wouldn't work whenever another process was running in the background, which is why I added the error message `please try again later`. I haven't been able to connect to tmpo from the website, even once.

Let's address this in the next meeting.
