### ISSUE TITLE
Speed up the fluksoapi.consolidate_sensor method or change data handling 

### ISSUE THREAD

**Issue by saroele** [opengridcc/opengrid#8]
The current synchronization of the data is based on consolidation of all available data to a single csv per sensor.  The consolidation is extremely slow, probably due to the combine_first method.  

There are some solutions:
1. replace the combine_first by a append operation? 
2. get rid of the idea that we need 1 file per sensor
3. switch to tmpo
4. switch to database

Not really a priority now, we can develop some data analysis scripts with the data we have.  Premature optimization is the root of all evil...

**Comment by kdebrab** [comment]
Since not all sensors use tmpo yet, I had a look at how to speed up the data synchronization:

1. Basic profiling with time.time() prints showed me that roughly 60% of time is spent in fluksoapi.save_csv and most of the remaining 40% in fluksoapi.load_csv. Compared to these, the time spent in combine_first is not significant.

2. Have a look at http://pandas.pydata.org/pandas-docs/stable/io.html#io-perf. Saving and reading hdf files is approximately 10 times faster than saving and reading csv files (or sql)!

So, it seems like we can speed up synchronization a lot (factor 10) simply by using hdf files instead of csv files.

**Comment by kdebrab** [comment]
Above code should work. The input files of consolidate_sensor can be csv, hdf or both. The output file type of consolidate_sensor is now always hdf.

I Synchronized from scratch using the 'Synchronize data' notebook, thus downloading 175 zip files (one for each day), unzipping them into csv files (one for each day and sensor) and consolidating these into 68 hdf files (one for each sensor). The timing of all this with the new code:

Download time: 169.105000019 s (3 min)
Unzip time: 364.179999828 s (6 min)
Consolidate time: 1343.69799995 s (22 min)
Total time: 1512.80299997 s (25 min)

That seems acceptable to me.
